AWSTemplateFormatVersion: "2010-09-09"
Description: This is a template for bootstrap CloudFormation. You may customize your resources in this template which will be deployed to new accounts automatically.

Parameters:
  AdminUsername:
    Type: String
    Description: Username for the Admin user
    Default: 'LZ-ADMIN'
  AdminPassword:
    Type: String
    NoEcho: True
    MinLength: 1
    Description: Password for the Admin user, Please change to your own password.
    Default: "ChangeToYourOwnP@ssw0rd"

Resources:
  Admin:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref AdminUsername
      Path: "/"
      LoginProfile:
        Password: !Ref AdminPassword
        PasswordResetRequired: True
      ManagedPolicyArns: 
        - "arn:aws-cn:iam::aws:policy/AdministratorAccess"